# Generated by Django 4.2.9 on 2024-03-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved')], default=1),
        ),
    ]
