# Generated by Django 4.2.9 on 2024-04-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_matchhistory_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='loses_stats',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wins_stats',
        ),
    ]
