# Generated by Django 4.2.9 on 2024-03-04 09:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(unique=True, validators=[main.models.validate_display_name], verbose_name='display name'),
        ),
    ]
