# Generated by Django 4.2.9 on 2024-04-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_loses_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.jpg', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
