# Generated by Django 4.2.9 on 2024-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
