# Generated by Django 4.2.9 on 2024-04-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userstatus_status_userstatus_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
