# Generated by Django 4.2.9 on 2024-04-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_is_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
