# Generated by Django 4.2.9 on 2024-04-28 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_gameinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present_1', models.BooleanField(default=False)),
                ('is_present_2', models.BooleanField(default=False)),
                ('game_id', models.CharField(max_length=32, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='match date')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
