# Generated by Django 4.2.9 on 2024-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pairgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'Text'), (2, 'GameID')], default=1),
        ),
    ]
