# Generated by Django 4.2.9 on 2024-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_chatmessage_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairgame',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In progress'), (2, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='pairgame',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
