# Generated by Django 4.2.9 on 2024-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pairgame_status_alter_pairgame_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairgame',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pairgame',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
