# Generated by Django 4.2.9 on 2024-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tournament_status_alter_pairgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairgame',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In progress'), (2, 'Finished')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In progress'), (2, 'Finished'), (3, 'Canceled')], default=0),
        ),
    ]
