# Generated by Django 4.2.9 on 2024-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tournament_tournament_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='invitation_status',
            field=models.JSONField(default=dict),
        ),
    ]
