# Generated by Django 4.2.9 on 2024-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_tournament_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='extra_details',
            field=models.TextField(default=None),
        ),
    ]
