# Generated by Django 4.2.9 on 2024-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_pairgame_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current',
            field=models.IntegerField(default=0),
        ),
    ]
