# Generated by Django 4.2.9 on 2024-05-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tournament_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_otp_required',
            field=models.BooleanField(default=False),
        ),
    ]
