version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver_plus 0.0.0.0:8081 --cert-file localhost.crt
    volumes:
      - ./app/:/usr/src/app/
    ports: 
      - 8081:8081
    env_file:
      - ./.env.dev

  db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: